#!/usr/bin/env bash
# Render the Homebrew formula for Ma'at from a version + a checksums file.
#
# Usage: scripts/render-homebrew-formula.sh <version> <checksums-file>
#   <version>        release version, with or without leading 'v' (e.g. 0.1.0)
#   <checksums-file> sha256sum-format file (GoReleaser's dist/checksums.txt)
#
# Prints the formula to stdout. Pure: no network, no side effects. This is the
# single source of truth for the formula — the release workflow pipes its output
# into the tap repo. Run it locally to preview or regenerate the live formula.
set -euo pipefail

VERSION="${1:?usage: render-homebrew-formula.sh <version> <checksums-file>}"
VERSION="${VERSION#v}"
CHECKSUMS="${2:?usage: render-homebrew-formula.sh <version> <checksums-file>}"

if [[ ! -f "$CHECKSUMS" ]]; then
  echo "error: checksums file not found: $CHECKSUMS" >&2
  exit 1
fi

# Look up the sha256 for a given archive suffix by exact filename match.
# checksums.txt format is "<sha256>  <filename>" (sha256sum standard).
sha_for() {
  local file="maat_${VERSION}_$1"
  local sha
  sha="$(awk -v f="$file" '$2 == f { print $1 }' "$CHECKSUMS")"
  if [[ -z "$sha" ]]; then
    echo "error: no checksum for '$file' in $CHECKSUMS" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

DARWIN_ARM="$(sha_for darwin_arm64.tar.gz)"
DARWIN_AMD="$(sha_for darwin_amd64.tar.gz)"
LINUX_ARM="$(sha_for linux_arm64.tar.gz)"
LINUX_AMD="$(sha_for linux_amd64.tar.gz)"

BASE_URL="https://github.com/getmaat/maat/releases/download/v${VERSION}"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for Ma'at — documentation-as-code for humans and AI agents.
# Auto-generated by scripts/render-homebrew-formula.sh on each release.
# Do not edit by hand; changes are overwritten on the next release.
class Maat < Formula
  desc "Documentation-as-code for humans and AI agents"
  homepage "https://github.com/getmaat/maat"
  version "${VERSION}"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${BASE_URL}/maat_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM}"
    end
    on_intel do
      url "${BASE_URL}/maat_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/maat_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM}"
    end
    on_intel do
      url "${BASE_URL}/maat_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD}"
    end
  end

  def install
    bin.install "maat"
  end

  test do
    assert_match "maat #{version}", shell_output("#{bin}/maat --version")
  end
end
EOF
